"""
Django settings for example18 project.

Generated by 'django-admin startproject' using Django 1.8.18.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import django

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.join(BASE_DIR, "example18")


SITE_ID = 1

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*2$rhmg25-#et_b5nt)_oq*u5ymb!xo0*2xl#5(-!h#)m@&bqq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LANGUAGES = [
    ('en', 'English'),
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'django_version_viewer',
]

MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

print(django.VERSION)
if django.VERSION[0] == 1 and django.VERSION[1] > 7:
    middleware_added = [
        'django.middleware.security.SecurityMiddleware',
        'django.middleware.locale.LocaleMiddleware'
    ]
else:
    middleware_added = [
        'django.middleware.locale.LocaleMiddleware'
    ]

MIDDLEWARE_CLASSES = MIDDLEWARE_CLASSES + middleware_added


ROOT_URLCONF = 'example18.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'example18.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


ACCESSOR_CLASS_PATH = 'django_version_viewer.mixins.SuperuserAccessor'

PROJECT_ROOT = BASE_DIR = os.environ.get(
    "DJANGO_PROJECT_ROOT",
    os.path.abspath(os.path.dirname(__file__)))
ENVIRONMENT_ROOT = os.environ.get(
    "DJANGO_ENVIRONMENT_ROOT",
    os.path.abspath(os.path.join(PROJECT_ROOT, '..', '..', '..')))
LOG_ROOT = os.environ.get(
    "DJANGO_LOG_ROOT",
    os.path.abspath(os.path.join(ENVIRONMENT_ROOT, 'var', 'log')))
HTDOCS_ROOT = os.environ.get("DJANGO_HTDOCS_ROOT",
                             os.path.abspath(os.path.join(ENVIRONMENT_ROOT, 'htdocs')))
STATIC_ROOT = os.path.join(HTDOCS_ROOT, 'static')

# if you want to test an example project with djangocms
ENABLE_DJANGOCMS = (
    False
    if os.environ.get("ENABLE_DJANGOCMS", True) in ["", "False", False, "false"]
    else True)

if ENABLE_DJANGOCMS:
    CMS_TEMPLATES = [
        ('home.html', 'Home page template'),
    ]

    MIDDLEWARE_CLASSES += [
        'cms.middleware.user.CurrentUserMiddleware',
        'cms.middleware.page.CurrentPageMiddleware',
        'cms.middleware.toolbar.ToolbarMiddleware',
        'cms.middleware.language.LanguageCookieMiddleware',
    ]

    INSTALLED_APPS = [
        'djangocms_admin_style',
    ] + INSTALLED_APPS + [
        'cms',
        'menus',
        'treebeard',
        'sekizai',
        'easy_thumbnails',
        'mptt',
        'djangocms_text_ckeditor',
    ]

    TEMPLATES[0]['OPTIONS']['context_processors'] += [
        'sekizai.context_processors.sekizai',
        'cms.context_processors.cms_settings',
    ]
