language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9


env:
- DJANGO="Django>=1.7,<1.8"
- DJANGO="Django>=1.8,<1.9"
- DJANGO="Django>=1.9,<1.10"
- DJANGO="Django>=1.10,<1.11"
- DJANGO="Django>=1.11,<1.12"
- DJANGO="Django>=2.0,<3.0"
- DJANGO="Django>=3.0,<4.0"

matrix:
  exclude:
    - python: 3.5
      env: DJANGO="Django>=1.7,<1.8"
    - python: 3.7
      env: DJANGO="Django>=2.0,<4.0"
    - python: 3.8
      env: DJANGO="Django>=2.0,<4.0"
    - python: 3.9
      env: DJANGO="Django>=2.0,<4.0"
install:
  - pip install -qU $DJANGO
  - pip install -e .[testing]

script: ENABLE_DJANGOCMS=False coverage run ./example18/manage.py test django_version_viewer && flake8 .
