name: Github Actions - Run Tests
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[testing]
          pip install -r ./example22/requirements.txt

      - name: Run tests
        working-directory: ./example22
        run: python manage.py test django_version_viewer

      - name: Run flake
        run: flake8 .
