name: Github Actions - Run Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4      
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          - pip install -r ./example22/requirements.txt

      - name: Run tests
        run: ENABLE_DJANGOCMS=False coverage run ./example22/manage.py test django_version_viewer && flake8 .
